### ISSUE TITLE
3.2 tasks

### ISSUE THREAD

**Issue by jbfaden** [hapi-server/data-specification-schema#8]
The 3.2 schema changes need to be identified and the schema needs to be written.

**Comment by jbfaden** [comment]
- [ ] [Citation required aka Terms of Use](https://github.com/hapi-server/data-specification/issues/131)
- [ ] serve images and file names

**Comment by jbfaden** [comment]
Was "serverCitation" accepted?  It is not described in the documentation.

**Comment by jbfaden** [comment]
I've added a subschema for "stringType", which is used to serve images.

**Comment by rweigel** [comment]
diff hapi-3.1.0/HAPI-data-access-spec-3.1.0.md hapi-dev/HAPI-data-access-spec-dev.md

**Comment by rweigel** [comment]
https://github.com/hapi-server/data-specification/issues/131 is marked for consideration for 3.3.
